### PR TITLE
Added clickable widget functionality

### LINKED ISSUE #14: Thoughts on making the overlay widget clickable?
I find myself wanted to add a floating button to my project that changes behavior based on which navigation tab is selected. I think a really cool way to do that would be to make the overlay widget clickable. 
To get the functions for the click event, you could modify TabData. 

I imagine it going something like this:
```
class TabData {
  TabData({@required this.iconData, @required this.title, this.on_click});

  IconData iconData;
  String title;
  Function on_click;
  final UniqueKey key = UniqueKey();
}
```

```
bottomNavigationBar: FancyBottomNavigation(
        tabs: [
          TabData(iconData: Icons.search, title: "Search", callback_function_1),
          TabData(iconData: Icons.home, title: "Home", callback_function_2),
          TabData(iconData: Icons.settings, title: "Settings", callback_function_3)
        ],
        key: bottomNavigationKey,
        // select home page as initial position
        initialSelection: currentPage = 1,
        onTabChangedListener: (position) {
          setState(() {
            currentPage = position;
          });
        },
      ),
```

### PR DESCRIPTION
**Pull request by TheWithz**
My take to resolve #14

### CODE REVIEW

**Comment by tunitowen** [comment]
Sorry for the delay in replying.. I'm not a fan of each tab having to include an onClick function. Is there a way to make this optional?

**Comment by TheWithz** [comment]
It should already be entirely optional. The `TabData` class defines it as an optional named argument, so if you don't need it, you can just leave it out entirely. meaning, code this this:

```tabs: [
        TabData(iconData: Icons.home, title: "Home"),
        TabData(iconData: Icons.search, title: "Search"),
        TabData(iconData: Icons.shopping_cart, title: "Basket")
    ],```
Is still 100% valid.

**Comment by GroovinChip** [comment]
I'm a huge fan of this idea! Please add it in!

**Comment by tunitowen** [comment]
Happy with this, merging to develop. Will need to add to readme and bump version to release. Thanks

**Pull request merged**
